input {
  tcp {
    port => 4560
    codec => json
  }

  tcp {
    port => 50000
    codec => json
  }

  udp {
    port => 50000
    codec => json
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }

  if ![environment] {
    mutate {
      add_field => { "environment" => "dev" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://es:9200"]
    index => "springboot-logstash-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
