# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 浣犻渶瑕佷慨鏀箂ystem涓轰綘鑷韩绯荤粺鐨勪粨搴撳悕
services:
  # MCP 鏈嶅姟锛孋SDN 鍙戝笘锛屾敞鎰?CSDN_API_COOKIE 淇敼涓轰綘鐨勩€?
  mcp-server-csdn-app:
    # 璇剧▼浠ｇ爜锛歨ttps://gitcode.net/KnowledgePlanet/mcp-server-csdn
    #    image: fuzhengwei/mcp-server-csdn-app:1.1
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/mcp-server-csdn-app:1.1
    container_name: mcp-server-csdn-app
    restart: always
    ports:
      - "8101:8101"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8101
      - CSDN_API_CATEGORIES=Java鍦烘櫙闈㈣瘯瀹濆吀
      - CSDN_API_COOKIE=${CSDN_API_COOKIE:}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  # 璇剧▼浠ｇ爜锛歨ttps://gitcode.net/KnowledgePlanet/mcp-server-weixin
  # MCP 鏈嶅姟锛屽井淇″叕浼楀彿閫氱煡锛屾敞鎰?environment 涓嬬殑寰俊閰嶇疆淇敼涓轰綘鐨?https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
  mcp-server-weixin-app:
    #    image: fuzhengwei/mcp-server-weixin-app:1.1
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/mcp-server-weixin-app:1.1
    container_name: mcp-server-weixin-app
    restart: always
    ports:
      - "8102:8102"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8102
      - WEIXIN_API_ORIGINAL_ID=gh_e067c267e056
      - WEIXIN_API_APP_ID=wx5a228ff69e28a91f
      - WEIXIN_API_APP_SECRET=${WEIXIN_API_APP_SECRET}
      - WEIXIN_API_TEMPLATE_ID=O8qI6gy75F-bXfPiQugInTMLA0MRzaMff9WSBb16cFk
      - WEIXIN_API_TOUSER=or0Ab6ivwmypESVp_bYuk92T6SvU
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

